name: Run Rubocop and RSpec Actions
on: pull_request

jobs:
  Job-Rubocop:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby Env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true

      - name: Run install
        run: bundle install

      - name: Run rubocop
        run: bundle exec rubocop

  Job-RSpec:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby Env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true

      - name: Run install
        run: bundle install

      - name: Run tests
        run: bundle exec rspec